---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ekakivy3/public_html/testekak.ekak.in
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
   - /bin/cp -R index.css $DEPLOYPATH